# BPG CI/CD Pipeline
# This test suite does the following:
#   Sets up anaconda python
#   conda installs dependencies for rtree/shapely
#   pip installs BAG from ucb-art
#   pip installs BPG
#   TODO: runs BPG test suite

# Run this pipeline whenever a commit is pushed onto master
trigger:
  - master

# Run this pipeline whenever a pull request to master or release is executed
# This allows developers to iterate in PRs and get their changes to be clean
pr:
  - master
  - releases/*

# Perform all of these tests on Ubuntu
# TODO: Extend these tests to be run on Windows + MacOS
pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: 'Create Anaconda environment'

  - bash: |
      source activate myEnvironment
      conda install --yes --name myEnvironment numpy
      conda install --yes --name myEnvironment rtree
      conda install --yes --name myEnvironment shapely
    displayName: 'Install Anaconda dependencies'

  - bash: |
      source activate myEnvironment
      pip install git+https://github.com/ucb-art/BAG_Framework
      pip install .
    displayName: 'Install BAG and BPG'

  - bash: |
      source activate myEnvironment
      pip install pytest
      cd ..
      ls -la
      pwd
    displayName: 'Run BPG test suite'
