# BPG CI/CD Pipeline
# This test suite does the following:
#   Sets up anaconda python
#   conda installs dependencies for rtree/shapely
#   TODO: Clones BAG from ucb-art
#   pip installs BPG
#   TODO: runs BPG test suite

#trigger:
#  - master

# Run this pipeline whenever a pull request to master or release is executed
pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: 'Create Anaconda environment'

  - bash: |
      source activate myEnvironment
      conda install --yes --name myEnvironment numpy
      conda install --yes --name myEnvironment rtree
      conda install --yes --name myEnvironment shapely
    displayName: 'Install Anaconda dependencies'

  - bash: |
      source activate myEnvironment
      pwd
      ls -la
      pip install .
    displayName: 'Install BPG'
