#!/usr/bin/env python
"""
This module provides a command-line interface to using BPG
"""
import sys
import argparse


def run(args):
    """ Sources your bag_startup.py and runs """
    import BPG
    plm = BPG.PhotonicLayoutManager(spec_file=args.spec)

    # Generate the content list no matter what
    plm.generate_content()

    if args.gds:
        plm.generate_gds()

    # Flat gds generation, lsf, or dataprep requires generation of flat content list
    if args.flat_gds or args.lsf or args.dataprep:
        plm.generate_flat_content()

    if args.flat_gds:
        plm.generate_flat_gds()
    if args.lsf:
        plm.generate_lsf()
    if args.dataprep:
        plm.dataprep()
        plm.generate_dataprep_gds()


def test(args):
    print(sys.path)


def setup():
    """ Copy over files """
    from BPG.workspace_setup.setup import copy_files
    copy_files()


def get_cmd_line_args(arg_list):
    sys.path = [''] + sys.path
    parser = argparse.ArgumentParser()
    # List of possible arguments
    parser.add_argument('action', help='any basic action like run, newproject, etc.')
    parser.add_argument('-s', '--spec',
                        help='the spec file to be used',
                        )
    parser.add_argument('-c', '--config',
                        help='the bag config file to be used',
                        )

    # Output types
    parser.add_argument('--gds',
                        help='flag to generate a gds',
                        action='store_true'
                        )
    parser.add_argument('--flat_gds',
                        help='flag to generate a flat gds',
                        action='store_true'
                        )
    parser.add_argument('--lsf',
                        help='flag to generate a lsf',
                        action='store_true'
                        )
    parser.add_argument('--dataprep',
                        help='flag to run dataprep and generate a dataprep gds',
                        action='store_true')
    args = parser.parse_args(arg_list)
    return args


def main(arg_list):
    """ Entry point for actions that bpg can take """
    args = get_cmd_line_args(arg_list)
    # action switch statement
    if args.action == 'run':
        run(args)
    elif args.action == 'test':
        test(args)
    elif args.action == 'setup':
        setup()
    else:
        print('Invalid action')
        return -1


if __name__ == '__main__':
    # Grab the arguments, but ignore the name of the script that is being run
    main(sys.argv[1:])
